import type { ChartMetadata } from "@/lib/charts/metadata"

export const charts: readonly ChartMetadata[] = [
  // Recharts Family
  {
    id: "recharts-line-signal",
    slug: "line-signal",
    registryName: "line-signal",
    title: "Signal Line",
    description:
      "Focused single-series time-series visualization with restrained active-point emphasis, accessible keyboard exploration, and Plotcn semantic tokens.",
    engine: "recharts",
    renderer: "svg",
    status: "preview",
    difficulty: "beginner",
    category: "line",
    tags: ["recharts", "line", "signal", "time-series", "trend", "analytics", "accessible"],
    componentPath: "registry/recharts/line-signal.tsx",
    exportName: "SignalLine",
    dependencies: ["recharts"],
    registryDependencies: ["chart-container", "chart-state", "chart-tooltip", "chart-motion"],
    features: ["responsive", "animated", "interactive", "tooltip", "keyboard", "accessible-data"],
    dataShape: `interface SignalLineDatum {\n  date: string\n  value: number\n}`,
    snippet: `<SignalLine data={data} xKey="date" seriesKey="value" />`,
  },
  {
    id: "recharts-line-pulse",
    slug: "line-pulse",
    registryName: "line-pulse",
    title: "Pulse Line",
    description:
      "High-frequency operational trend visualization for rapidly changing metrics, rolling windows, and live telemetry surfaces.",
    engine: "recharts",
    renderer: "svg",
    status: "preview",
    difficulty: "intermediate",
    category: "line",
    tags: ["recharts", "line", "pulse", "operational", "telemetry", "streaming", "rolling-window"],
    componentPath: "registry/recharts/line-pulse.tsx",
    exportName: "PulseLine",
    dependencies: ["recharts"],
    registryDependencies: ["chart-container", "chart-state", "chart-tooltip", "chart-motion"],
    features: ["responsive", "animated", "interactive", "tooltip", "keyboard", "accessible-data"],
    dataShape: `interface PulseLineDatum {\n  timestamp: string\n  latency: number\n}`,
    snippet: `<PulseLine data={data} xKey="timestamp" seriesKey="latency" windowSize={30} showLatestPoint />`,
  },
  {
    id: "recharts-line-twin-compare",
    slug: "line-twin-compare",
    registryName: "line-twin-compare",
    title: "Twinline Compare",
    description:
      "Compare one primary series against one reference series with a strong visual hierarchy, synchronized inspection, precise delta context, and clean responsive behavior.",
    engine: "recharts",
    renderer: "svg",
    status: "preview",
    difficulty: "intermediate",
    category: "line",
    tags: ["recharts", "line", "comparison", "benchmark", "delta", "analytics", "accessible"],
    componentPath: "registry/recharts/line-twin-compare.tsx",
    exportName: "TwinlineCompare",
    dependencies: ["recharts"],
    registryDependencies: ["chart-container", "chart-state", "chart-tooltip", "chart-motion", "chart-legend"],
    features: ["responsive", "animated", "interactive", "tooltip", "keyboard", "accessible-data"],
    dataShape: `interface TwinlineCompareDatum {\n  date: string\n  current: number\n  previous: number\n}`,
    snippet: `<TwinlineCompare data={data} xKey="date" primaryKey="current" referenceKey="previous" primaryLabel="2024" referenceLabel="2023" />`,
  },
  {
    id: "recharts-line-range",
    slug: "line-range",
    registryName: "line-range",
    title: "Range Line",
    description:
      "Visualizes a central trend alongside a lower-to-upper interval envelope for forecasts, confidence intervals, and operational tolerance bands.",
    engine: "recharts",
    renderer: "svg",
    status: "preview",
    difficulty: "intermediate",
    category: "line",
    tags: ["recharts", "line", "range", "confidence-interval", "forecast", "envelope", "uncertainty", "accessible"],
    componentPath: "registry/recharts/line-range.tsx",
    exportName: "RangeLine",
    dependencies: ["recharts"],
    registryDependencies: ["chart-container", "chart-state", "chart-tooltip", "chart-motion"],
    features: ["responsive", "animated", "interactive", "tooltip", "keyboard", "accessible-data"],
    dataShape: `interface RangeLineDatum {\n  date: string\n  forecast: number\n  lower: number\n  upper: number\n}`,
    snippet: `<RangeLine data={data} xKey="date" valueKey="forecast" lowerKey="lower" upperKey="upper" label="Forecast" rangeLabel="95% Range" />`,
  },
  {
    id: "recharts-line-step-signal",
    slug: "line-step-signal",
    registryName: "line-step-signal",
    title: "Step Signal",
    description:
      "Stepped visualization for discrete changes that remain in effect until the next observation, communicating quotas, pricing plans, and configuration states.",
    engine: "recharts",
    renderer: "svg",
    status: "preview",
    difficulty: "intermediate",
    category: "line",
    tags: ["recharts", "line", "step", "step-signal", "state", "plan", "quota", "discrete", "accessible"],
    componentPath: "registry/recharts/line-step-signal.tsx",
    exportName: "StepSignal",
    dependencies: ["recharts"],
    registryDependencies: ["chart-container", "chart-state", "chart-tooltip", "chart-motion"],
    features: ["responsive", "animated", "interactive", "tooltip", "keyboard", "accessible-data"],
    dataShape: `interface StepSignalDatum {\n  date: string\n  limit: number\n}`,
    snippet: `<StepSignal data={data} xKey="date" seriesKey="limit" />`,
  },
  {
    id: "recharts-line-milestones",
    slug: "line-milestones",
    registryName: "line-milestones",
    title: "Milestone Line",
    description:
      "Time-series trend with sparse event annotations and milestone pins for releases, incidents, launches, and policy changes.",
    engine: "recharts",
    renderer: "svg",
    status: "preview",
    difficulty: "intermediate",
    category: "line",
    tags: ["recharts", "line", "milestone", "events", "annotations", "releases", "launches", "time-series", "accessible"],
    componentPath: "registry/recharts/line-milestones.tsx",
    exportName: "MilestoneLine",
    dependencies: ["recharts"],
    registryDependencies: ["chart-container", "chart-state", "chart-tooltip", "chart-motion"],
    features: ["responsive", "animated", "interactive", "tooltip", "keyboard", "accessible-data"],
    dataShape: `interface MilestoneDatum {\n  date: string\n  users: number\n}\n\ninterface MilestoneItem {\n  id: string\n  x: string\n  label: string\n  description?: string\n}`,
    snippet: `<MilestoneLine data={data} xKey="date" series={{ key: "users", label: "Active users" }} milestones={milestones} />`,
  },
  {
    id: "recharts-line-threshold",
    slug: "line-threshold",
    registryName: "line-threshold",
    title: "Threshold Line",
    description:
      "Trend visualization with configurable target, limit, warning, and operating threshold regions.",
    engine: "recharts",
    renderer: "svg",
    status: "preview",
    difficulty: "intermediate",
    category: "line",
    tags: ["recharts", "line", "threshold", "target", "sla", "limits", "bands", "operating-region", "accessible"],
    componentPath: "registry/recharts/line-threshold.tsx",
    exportName: "ThresholdLine",
    dependencies: ["recharts"],
    registryDependencies: ["chart-container", "chart-state", "chart-tooltip", "chart-motion"],
    features: ["responsive", "animated", "interactive", "tooltip", "keyboard", "accessible-data"],
    dataShape: `interface ThresholdDatum {\n  time: string\n  latency: number\n}\n\ntype ThresholdDefinition = \n  | { id: string; kind: 'line'; value: number; label: string; color?: string }\n  | { id: string; kind: 'region'; from?: number; to?: number; label: string; color?: string }`,
    snippet: `<ThresholdLine data={data} xKey="time" series={{ key: "latency", label: "P95 latency" }} thresholds={thresholds} />`,
  },
  {
    id: "recharts-line-focus",
    slug: "line-focus",
    registryName: "line-focus",
    title: "Focus Line",
    description:
      "An interaction-first time-series line optimized for precise keyboard focus, pointer/touch scrubbing, crosshair inspection, and persistent locked tooltips.",
    engine: "recharts",
    renderer: "svg",
    status: "preview",
    difficulty: "intermediate",
    category: "line",
    tags: ["recharts", "line", "focus", "inspection", "scrubbing", "keyboard-navigation", "lockable-tooltip", "accessible"],
    componentPath: "registry/recharts/line-focus.tsx",
    exportName: "FocusLine",
    dependencies: ["recharts"],
    registryDependencies: ["chart-container", "chart-state", "chart-tooltip", "chart-motion"],
    features: ["responsive", "animated", "interactive", "tooltip", "keyboard", "accessible-data"],
    dataShape: `interface FocusLineDatum {\n  time: string\n  latency: number | null\n}`,
    snippet: `<FocusLine data={data} xKey="time" series={{ key: "latency", label: "P95 latency" }} lockableTooltip />`,
  },
  {
    id: "recharts-line-multi-signal",
    slug: "line-multi-signal",
    registryName: "line-multi-signal",
    title: "Multi-Signal Line",
    description:
      "A multi-series time-series line chart with deterministic series identity, stable color assignment, readable shared tooltips, responsive legend controls, and truthful missing-series behavior.",
    engine: "recharts",
    renderer: "svg",
    status: "preview",
    difficulty: "intermediate",
    category: "line",
    tags: ["recharts", "line", "multi-signal", "multi-series", "legend-toggling", "deterministic-colors", "time-series", "accessible"],
    componentPath: "registry/recharts/line-multi-signal.tsx",
    exportName: "MultiSignalLine",
    dependencies: ["recharts"],
    registryDependencies: ["chart-container", "chart-state", "chart-tooltip", "chart-motion"],
    features: ["responsive", "animated", "interactive", "tooltip", "keyboard", "accessible-data"],
    dataShape: `interface MultiSignalDatum {\n  month: string\n  web: number | null\n  ios: number | null\n  android: number | null\n}`,
    snippet: `<MultiSignalLine\n  data={data}\n  xKey="month"\n  series={[\n    { key: "web", label: "Web" },\n    { key: "ios", label: "iOS" },\n    { key: "android", label: "Android" },\n  ]}\n/>`,
  },
  {
    id: "recharts-line-forecast",
    slug: "line-forecast",
    registryName: "line-forecast",
    title: "Forecast Line",
    description:
      "Observed-versus-forecast time-series with explicit prediction styling, truthful boundary transitions, and optional uncertainty range treatment.",
    engine: "recharts",
    renderer: "svg",
    status: "preview",
    difficulty: "intermediate",
    category: "line",
    tags: ["recharts", "line", "forecast", "prediction", "confidence-interval", "uncertainty", "actual-vs-forecast", "time-series", "accessible"],
    componentPath: "registry/recharts/line-forecast.tsx",
    exportName: "ForecastLine",
    dependencies: ["recharts"],
    registryDependencies: ["chart-container", "chart-state", "chart-tooltip", "chart-motion"],
    features: ["responsive", "animated", "interactive", "tooltip", "keyboard", "accessible-data"],
    dataShape: `interface ForecastDatum {\n  month: string\n  actual: number | null\n  forecast: number | null\n  lower?: number | null\n  upper?: number | null\n}`,
    snippet: `<ForecastLine\n  data={data}\n  xKey="month"\n  series={{\n    actualKey: "actual",\n    forecastKey: "forecast",\n    lowerKey: "lower",\n    upperKey: "upper",\n  }}\n/>`,
  },
  {
    id: "recharts-area-prism",
    slug: "area-prism",
    registryName: "area-prism",
    title: "Prism Area",
    description:
      "Single-series magnitude area chart with restrained semantic fill, explicit baseline semantics, and Plotcn shared inspection.",
    engine: "recharts",
    renderer: "svg",
    status: "preview",
    difficulty: "intermediate",
    category: "area",
    tags: ["recharts", "area", "prism", "magnitude", "baseline", "volume", "time-series", "accessible"],
    componentPath: "registry/recharts/area-prism.tsx",
    exportName: "PrismArea",
    dependencies: ["recharts"],
    registryDependencies: ["chart-container", "chart-state", "chart-tooltip", "chart-motion"],
    features: ["responsive", "animated", "interactive", "tooltip", "keyboard", "accessible-data"],
    dataShape: `interface PrismAreaDatum {\n  date: string\n  requests: number | null\n}`,
    snippet: `<PrismArea\n  data={data}\n  xKey="date"\n  series={{\n    key: "requests",\n    label: "API Requests",\n  }}\n/>`,
  },
  {
    id: "recharts-area-stack-flow",
    slug: "area-stack-flow",
    registryName: "area-stack-flow",
    title: "Stack Flow Area",
    description:
      "Additive multi-series stacked area chart with deterministic stack identity, truthful missing-value semantics, and contribution-over-time inspection.",
    engine: "recharts",
    renderer: "svg",
    status: "preview",
    difficulty: "advanced",
    category: "area",
    tags: ["recharts", "area", "stack", "composition", "additive", "multi-series", "accessible"],
    componentPath: "registry/recharts/area-stack-flow.tsx",
    exportName: "StackFlowArea",
    dependencies: ["recharts"],
    registryDependencies: ["chart-container", "chart-state", "chart-tooltip", "chart-motion"],
    features: ["responsive", "animated", "interactive", "tooltip", "keyboard", "accessible-data"],
    dataShape: `interface StackFlowDatum {\n  month: string\n  web: number | null\n  ios: number | null\n  android: number | null\n}`,
    snippet: `<StackFlowArea\n  data={data}\n  xKey="month"\n  series={[\n    { key: "web", label: "Web" },\n    { key: "ios", label: "iOS" },\n    { key: "android", label: "Android" },\n  ]}\n/>`,
  },
  {
    id: "recharts-area-percent-stream",
    slug: "area-percent-stream",
    registryName: "area-percent-stream",
    title: "Percent Stream Area",
    description:
      "100% normalized stacked area chart for tracking how each contributor's share of the visible whole evolves over an ordered domain.",
    engine: "recharts",
    renderer: "svg",
    status: "preview",
    difficulty: "advanced",
    category: "area",
    tags: ["recharts", "area", "percent", "stream", "composition", "normalized", "share", "multi-series", "accessible"],
    componentPath: "registry/recharts/area-percent-stream.tsx",
    exportName: "PercentStreamArea",
    dependencies: ["recharts"],
    registryDependencies: ["chart-container", "chart-state", "chart-tooltip", "chart-motion"],
    features: ["responsive", "animated", "interactive", "tooltip", "keyboard", "accessible-data"],
    dataShape: `interface TrafficMixDatum {\n  month: string\n  web: number | null\n  ios: number | null\n  android: number | null\n}`,
    snippet: `<PercentStreamArea\n  data={data}\n  xKey="month"\n  series={[\n    { key: "web", label: "Web" },\n    { key: "ios", label: "iOS" },\n    { key: "android", label: "Android" },\n  ]}\n/>`,
  },
  {
    id: "recharts-area-range",
    slug: "area-range",
    registryName: "area-range",
    title: "Range Area",
    description:
      "Bounded area visualization for showing a lower/upper envelope across an ordered domain, with optional central trend, truthful interval semantics, and explicit missing-bound behavior.",
    engine: "recharts",
    renderer: "svg",
    status: "preview",
    difficulty: "intermediate",
    category: "area",
    tags: ["recharts", "area", "range", "envelope", "interval", "tolerance", "min-max", "uncertainty", "accessible"],
    componentPath: "registry/recharts/area-range.tsx",
    exportName: "RangeArea",
    dependencies: ["recharts"],
    registryDependencies: ["chart-container", "chart-state", "chart-tooltip", "chart-motion"],
    features: ["responsive", "animated", "interactive", "tooltip", "keyboard", "accessible-data"],
    dataShape: `interface LatencyRangeDatum {\n  time: string\n  min: number | null\n  max: number | null\n  median?: number | null\n}`,
    snippet: `<RangeArea\n  data={data}\n  xKey="time"\n  series={{\n    lowerKey: "min",\n    upperKey: "max",\n    valueKey: "median",\n    label: "Latency envelope",\n  }}\n/>`,
  },
  {
    id: "recharts-area-comparison",
    slug: "area-comparison",
    registryName: "area-comparison",
    title: "Comparison Area",
    description:
      "Two-series area visualization for comparing a primary magnitude against a reference magnitude across an ordered domain, using restrained overlap, deterministic semantic identity, and shared Y-scale.",
    engine: "recharts",
    renderer: "svg",
    status: "preview",
    difficulty: "intermediate",
    category: "area",
    tags: ["recharts", "area", "comparison", "overlap", "primary-vs-reference", "delta", "two-series", "accessible"],
    componentPath: "registry/recharts/area-comparison.tsx",
    exportName: "ComparisonArea",
    dependencies: ["recharts"],
    registryDependencies: ["chart-container", "chart-state", "chart-tooltip", "chart-motion"],
    features: ["responsive", "animated", "interactive", "tooltip", "keyboard", "accessible-data"],
    dataShape: `interface ComparisonAreaDatum {\n  month: string\n  current: number | null\n  previous: number | null\n}`,
    snippet: `<ComparisonArea\n  data={data}\n  xKey="month"\n  series={{\n    primary: { key: "current", label: "Current year" },\n    reference: { key: "previous", label: "Previous year" },\n  }}\n/>`,
  },
  {
    id: "recharts-area-gradient-depth",
    slug: "area-gradient-depth",
    registryName: "area-gradient-depth",
    title: "Gradient Depth Area",
    description:
      "Single-series area visualization with a semantic fade-to-surface fill that adds restrained depth without encoding an additional variable.",
    engine: "recharts",
    renderer: "svg",
    status: "preview",
    difficulty: "intermediate",
    category: "area",
    tags: ["recharts", "area", "gradient", "depth", "surface", "magnitude", "time-series", "accessible"],
    componentPath: "registry/recharts/area-gradient-depth.tsx",
    exportName: "GradientDepthArea",
    dependencies: ["recharts"],
    registryDependencies: ["chart-container", "chart-state", "chart-tooltip", "chart-motion"],
    features: ["responsive", "animated", "interactive", "tooltip", "keyboard", "accessible-data"],
    dataShape: `interface GradientDepthAreaDatum {\n  date: string\n  requests: number | null\n}`,
    snippet: `<GradientDepthArea\n  data={data}\n  xKey="date"\n  series={{\n    key: "requests",\n    label: "Requests",\n  }}\n/>`,
  },
  {
    id: "recharts-area-baseline",
    slug: "area-baseline",
    registryName: "area-baseline",
    title: "Baseline Area",
    description:
      "Single-series area visualization showing values above and below an explicit quantitative reference baseline with truthful deviation semantics.",
    engine: "recharts",
    renderer: "svg",
    status: "preview",
    difficulty: "intermediate",
    category: "area",
    tags: ["recharts", "area", "baseline", "deviation", "reference", "above-below", "time-series", "accessible"],
    componentPath: "registry/recharts/area-baseline.tsx",
    exportName: "BaselineArea",
    dependencies: ["recharts"],
    registryDependencies: ["chart-container", "chart-state", "chart-tooltip", "chart-motion"],
    features: ["responsive", "animated", "interactive", "tooltip", "keyboard", "accessible-data"],
    dataShape: `interface BaselineAreaDatum {\n  day: string\n  utilization: number | null\n}`,
    snippet: `<BaselineArea\n  data={data}\n  xKey="day"\n  series={{\n    key: "utilization",\n    label: "Utilization",\n  }}\n  baseline={75}\n/>`,
  },
  {
    id: "recharts-area-interactive",
    slug: "area-interactive",
    registryName: "area-interactive",
    title: "Interactive Area",
    description:
      "Inspection-first area visualization with nearest-X selection, observation-aligned crosshair, keyboard navigation, and a persistent lockable tooltip.",
    engine: "recharts",
    renderer: "svg",
    status: "preview",
    difficulty: "intermediate",
    category: "area",
    tags: ["recharts", "area", "interactive", "inspection", "nearest-x", "crosshair", "lockable", "keyboard", "touch", "accessible"],
    componentPath: "registry/recharts/area-interactive.tsx",
    exportName: "InteractiveArea",
    dependencies: ["recharts", "@hugeicons/react", "@hugeicons/core-free-icons"],
    registryDependencies: ["chart-container", "chart-state", "chart-tooltip", "chart-motion"],
    features: ["responsive", "animated", "interactive", "tooltip", "keyboard", "accessible-data"],
    dataShape: `interface ApiTrafficDatum {\n  date: string\n  requests: number | null\n}`,
    snippet: `<InteractiveArea\n  data={data}\n  xKey="date"\n  series={{\n    key: "requests",\n    label: "Requests",\n  }}\n/>`,
  },
  {
    id: "recharts-bar-signal",
    slug: "bar-signal",
    registryName: "bar-signal",
    title: "Signal Bars",
    description:
      "Canonical zero-anchored bars for discrete categorical comparison with stable ordering, grouped series, and category-centric inspection.",
    engine: "recharts",
    renderer: "svg",
    status: "preview",
    difficulty: "beginner",
    category: "bar",
    tags: ["recharts", "bar", "signal", "categorical", "grouped-series", "zero-baseline", "signed-values", "accessible"],
    componentPath: "registry/recharts/bar-signal.tsx",
    exportName: "SignalBars",
    dependencies: ["recharts"],
    registryDependencies: ["chart-container", "chart-state", "chart-tooltip", "chart-motion", "chart-legend"],
    features: ["responsive", "animated", "interactive", "tooltip", "legend", "keyboard", "accessible-data"],
    dataShape: `interface RegionDatum {\n  region: string\n  web: number | null\n  mobile: number | null\n}`,
    snippet: `<SignalBars\n  data={data}\n  categoryKey="region"\n  series={[\n    { key: "web", label: "Web" },\n    { key: "mobile", label: "Mobile" },\n  ]}\n/>`,
  },
  {
    id: "recharts-bar-group-compare",
    slug: "bar-group-compare",
    registryName: "bar-group-compare",
    title: "Group Compare Bars",
    description:
      "Side-by-side peer measures within stable categorical groups, with shared quantitative scaling, deterministic series identity, and category-centric inspection.",
    engine: "recharts",
    renderer: "svg",
    status: "preview",
    difficulty: "intermediate",
    category: "bar",
    tags: ["recharts", "bar", "grouped", "multi-series", "comparison", "shared-scale", "categorical", "accessible"],
    componentPath: "registry/recharts/bar-group-compare.tsx",
    exportName: "GroupCompareBars",
    dependencies: ["recharts"],
    registryDependencies: ["chart-container", "chart-state", "chart-tooltip", "chart-motion"],
    features: ["responsive", "animated", "interactive", "tooltip", "legend", "keyboard", "accessible-data"],
    dataShape: `interface GroupCompareDatum {\n  quarter: string\n  current: number | null\n  previous: number | null\n  target?: number | null\n}`,
    snippet: `<GroupCompareBars\n  data={data}\n  categoryKey="quarter"\n  series={[\n    { key: "current", label: "Current year" },\n    { key: "previous", label: "Previous year" },\n  ]}\n/>`,
  },
  {
    id: "recharts-bar-stack-ledger",
    slug: "bar-stack-ledger",
    registryName: "bar-stack-ledger",
    title: "Stack Ledger Bars",
    description:
      "Additive stacked bars for multi-series categorical composition with stable contributor identity, truthful totals, and category-centric inspection.",
    engine: "recharts",
    renderer: "svg",
    status: "preview",
    difficulty: "intermediate",
    category: "bar",
    tags: ["recharts", "bar", "stacked", "additive", "totals", "categorical", "composition", "accessible"],
    componentPath: "registry/recharts/bar-stack-ledger.tsx",
    exportName: "StackLedgerBars",
    dependencies: ["recharts"],
    registryDependencies: ["chart-container", "chart-state", "chart-tooltip", "chart-motion"],
    features: ["responsive", "animated", "interactive", "tooltip", "legend", "keyboard", "accessible-data"],
    dataShape: `interface StackLedgerDatum {\n  quarter: string\n  compute: number | null\n  storage: number | null\n  network: number | null\n}`,
    snippet: `<StackLedgerBars\n  data={data}\n  categoryKey="quarter"\n  series={[\n    { key: "compute", label: "Compute" },\n    { key: "storage", label: "Storage" },\n    { key: "network", label: "Network" },\n  ]}\n/>`,
  },
  {
    id: "recharts-bar-percent-stack",
    slug: "bar-percent-stack",
    registryName: "bar-percent-stack",
    title: "Percent Stack Bars",
    description:
      "100% normalized stacked bars for comparing categorical composition while preserving raw contributor values, stable identity, and truthful zero/missing semantics.",
    engine: "recharts",
    renderer: "svg",
    status: "preview",
    difficulty: "intermediate",
    category: "bar",
    tags: ["recharts", "bar", "stacked", "normalized", "100-percent", "share-of-whole", "categorical", "composition", "accessible"],
    componentPath: "registry/recharts/bar-percent-stack.tsx",
    exportName: "PercentStackBars",
    dependencies: ["recharts"],
    registryDependencies: ["chart-container", "chart-state", "chart-tooltip", "chart-motion"],
    features: ["responsive", "animated", "interactive", "tooltip", "legend", "keyboard", "accessible-data"],
    dataShape: `interface PercentStackDatum {\n  segment: string\n  monthly: number | null\n  annual: number | null\n  multiYear?: number | null\n}`,
    snippet: `<PercentStackBars\n  data={data}\n  categoryKey="segment"\n  series={[\n    { key: "monthly", label: "Monthly" },\n    { key: "annual", label: "Annual" },\n    { key: "multiYear", label: "Multi-year" },\n  ]}\n/>`,
  },
  {
    id: "recharts-bar-diverging",
    slug: "bar-diverging",
    registryName: "bar-diverging",
    title: "Diverging Bars",
    description:
      "Signed categorical bars extending above/below or left/right from a neutral reference, with symmetric scaling, direction-aware geometry, and factual deviation semantics.",
    engine: "recharts",
    renderer: "svg",
    status: "preview",
    difficulty: "intermediate",
    category: "bar",
    tags: ["recharts", "bar", "diverging", "signed", "deviation", "baseline", "symmetric", "accessible"],
    componentPath: "registry/recharts/bar-diverging.tsx",
    exportName: "DivergingBars",
    dependencies: ["recharts"],
    registryDependencies: ["chart-container", "chart-state", "chart-tooltip", "chart-motion"],
    features: ["responsive", "animated", "interactive", "tooltip", "legend", "keyboard", "accessible-data"],
    dataShape: `interface DivergingDatum {\n  region: string\n  variance: number | null\n}`,
    snippet: `<DivergingBars\n  data={data}\n  categoryKey="region"\n  series={{\n    key: "variance",\n    label: "Variance from Plan",\n  }}\n  baseline={0}\n/>`,
  },
  {
    id: "recharts-bar-bullet",
    slug: "bar-bullet",
    registryName: "bar-bullet",
    title: "Bullet Bars",
    description:
      "Compact actual-versus-target bars for operational scorecards, with per-category target markers, truthful delta semantics, and responsive row-based inspection.",
    engine: "recharts",
    renderer: "svg",
    status: "preview",
    difficulty: "intermediate",
    category: "bar",
    tags: ["recharts", "bar", "bullet", "target", "scorecard", "delta", "horizontal", "accessible"],
    componentPath: "registry/recharts/bar-bullet.tsx",
    exportName: "BulletBars",
    dependencies: ["recharts"],
    registryDependencies: ["chart-container", "chart-state", "chart-tooltip", "chart-motion"],
    features: ["responsive", "animated", "interactive", "tooltip", "legend", "keyboard", "accessible-data"],
    dataShape: `interface ServiceSlaDatum {\n  service: string\n  actual: number | null\n  target: number | null\n}`,
    snippet: `<BulletBars\n  data={data}\n  categoryKey="service"\n  series={{\n    valueKey: "actual",\n    targetKey: "target",\n    label: "Availability",\n  }}\n/>`,
  },
  {
    id: "recharts-bar-variance",
    slug: "bar-variance",
    registryName: "bar-variance",
    title: "Variance Bars",
    description:
      "Actual-versus-plan delta bars centered on a truthful zero-variance baseline, with neutral signed semantics and auditable source values.",
    engine: "recharts",
    renderer: "svg",
    status: "preview",
    difficulty: "intermediate",
    category: "bar",
    tags: ["recharts", "bar", "variance", "actual-vs-plan", "delta", "zero-baseline", "signed", "accessible"],
    componentPath: "registry/recharts/bar-variance.tsx",
    exportName: "VarianceBars",
    dependencies: ["recharts"],
    registryDependencies: ["chart-container", "chart-state", "chart-tooltip", "chart-motion"],
    features: ["responsive", "animated", "interactive", "tooltip", "legend", "keyboard", "accessible-data"],
    dataShape: `interface BudgetVarianceDatum {\n  segment: string\n  actual: number | null\n  plan: number | null\n}`,
    snippet: `<VarianceBars\n  data={data}\n  categoryKey="segment"\n  series={{\n    actualKey: "actual",\n    planKey: "plan",\n    label: "Budget Variance",\n  }}\n/>`,
  },
  {
    id: "recharts-bar-interval",
    slug: "bar-interval",
    registryName: "bar-interval",
    title: "Interval Bars",
    description:
      "Floating categorical ranges with explicit start and end bounds for schedules, maintenance windows, operating durations, and bounded quantitative intervals.",
    engine: "recharts",
    renderer: "svg",
    status: "preview",
    difficulty: "intermediate",
    category: "bar",
    tags: ["recharts", "bar", "interval", "range", "duration", "schedule", "floating", "accessible"],
    componentPath: "registry/recharts/bar-interval.tsx",
    exportName: "IntervalBars",
    dependencies: ["recharts"],
    registryDependencies: ["chart-container", "chart-state", "chart-tooltip", "chart-motion"],
    features: ["responsive", "animated", "interactive", "tooltip", "legend", "keyboard", "accessible-data"],
    dataShape: `interface ServiceScheduleDatum {\n  service: string\n  start: number | null\n  end: number | null\n}`,
    snippet: `<IntervalBars\n  data={data}\n  categoryKey="service"\n  series={{\n    startKey: "start",\n    endKey: "end",\n    label: "Maintenance Window",\n  }}\n/>`,
  },
  {
    id: "recharts-bar-interactive",
    slug: "bar-interactive",
    registryName: "bar-interactive",
    title: "Interactive Bars",
    description:
      "Category-first bar inspection with a precise band cursor, persistent touch locking, and keyboard traversal across single or grouped categorical series.",
    engine: "recharts",
    renderer: "svg",
    status: "preview",
    difficulty: "advanced",
    category: "bar",
    tags: ["recharts", "bar", "interactive", "multi-series", "band-cursor", "touch-lock", "keyboard", "accessible"],
    componentPath: "registry/recharts/bar-interactive.tsx",
    exportName: "InteractiveBars",
    dependencies: ["recharts"],
    registryDependencies: ["chart-container", "chart-state", "chart-tooltip", "chart-motion"],
    features: ["responsive", "animated", "interactive", "tooltip", "legend", "keyboard", "accessible-data"],
    dataShape: `interface QuarterlyRevenueDatum {\n  quarter: string\n  product: number | null\n  services: number | null\n  enterprise: number | null\n}`,
    snippet: `<InteractiveBars\n  data={data}\n  categoryKey="quarter"\n  series={[\n    { key: "product", label: "Product" },\n    { key: "services", label: "Services" },\n    { key: "enterprise", label: "Enterprise" },\n  ]}\n/>`,
  },
  {
    id: "recharts-donut-basic",
    slug: "donut-basic",
    registryName: "donut-basic",
  "title": "Basic Donut Chart",
  "description": "Proportional category breakdown with a configurable inner radius, legend, and tooltips.",
  "engine": "recharts",
  "renderer": "svg",
  "status": "stable",
  "difficulty": "beginner",
  "category": "pie",
  "tags": [
    "recharts",
    "donut",
    "composition",
    "proportions"
  ],
  "componentPath": "registry/recharts/donut-basic.tsx",
  "exportName": "DonutBasic",
  "dependencies": [
    "recharts"
  ],
  "registryDependencies": [
    "chart-container",
    "chart-motion",
    "chart-tooltip"
  ],
  "features": [
    "responsive",
    "animated",
    "interactive",
    "tooltip",
    "legend"
  ],
  "dataShape": "interface DonutDatum {\n  label: string\n  value: number\n}",
  "snippet": "<DonutBasic data={data} />"
},

  // D3.js Family
  {
    id: "d3-animated-line",
    slug: "animated-line",
    registryName: "d3-animated-line",
    title: "D3 Animated Line Plot",
    description:
      "Direct SVG path rendering powered by D3 scales and stroke-dashoffset drawing animation using native SVG.",
    engine: "d3",
    renderer: "svg",
    status: "beta",
    difficulty: "advanced",
    category: "line",
    tags: ["d3", "line", "svg", "animation", "precision", "scales"],
    componentPath: "registry/d3/d3-animated-line.tsx",
    exportName: "D3AnimatedLine",
    dependencies: ["d3-scale","d3-shape","d3-array"],
    registryDependencies: ["chart-motion"],
    features: ["responsive", "animated"],
    dataShape: `interface D3Point {\n  x: number\n  y: number\n}`,
    snippet: `<D3AnimatedLine data={points} color="#10b981" />`,
  },
  {
    id: "d3-force-network",
    slug: "force-network",
    registryName: "d3-force-network",
    title: "D3 Force-Directed Network",
    description:
      "Force-directed network with a settling physics simulation, labeled nodes, and automatic centering.",
    engine: "d3",
    renderer: "svg",
    status: "beta",
    difficulty: "advanced",
    category: "network",
    tags: [
      "d3",
      "network",
      "physics",
      "force-directed",
      "simulation",
      "topology",
    ],
    componentPath: "registry/d3/d3-force-network.tsx",
    exportName: "D3ForceNetwork",
    dependencies: ["d3-force"],
    registryDependencies: [],
    features: ["responsive", "animated"],
    dataShape: `interface NetworkData {\n  nodes: { id: string; label: string; group?: number }[]\n  links: { source: string; target: string; value?: number }[]\n}`,
    snippet: `<D3ForceNetwork nodes={nodes} links={links} />`,
  },

  // Google Charts Family
  {
    id: "google-line",
    slug: "line",
    registryName: "google-line",
    title: "Google Core Line Chart",
    description:
      "Google Visualization corechart line with dark theme styling, smooth spline interpolation, and singleton loader deduplication.",
    engine: "google",
    renderer: "google-runtime",
    status: "stable",
    difficulty: "intermediate",
    category: "line",
    tags: ["google", "line", "corechart", "hosted-runtime", "spline"],
    componentPath: "registry/google/google-line.tsx",
    exportName: "GoogleLine",
    dependencies: [],
    registryDependencies: ["google-chart-container","google-chart-loader"],
    features: ["responsive", "interactive", "tooltip"],
    dataShape: `interface GoogleLineDatum {\n  label: string\n  value: number\n}`,
    snippet: `<GoogleLine data={data} color="#10b981" />`,
  },
  {
    id: "google-bar",
    slug: "bar",
    registryName: "google-bar",
    title: "Google Column Bar Chart",
    description:
      "Google ColumnChart with clean vertical bars, transparent background, and dark theme grid lines.",
    engine: "google",
    renderer: "google-runtime",
    status: "stable",
    difficulty: "intermediate",
    category: "bar",
    tags: ["google", "bar", "column", "corechart", "metrics"],
    componentPath: "registry/google/google-bar.tsx",
    exportName: "GoogleBar",
    dependencies: [],
    registryDependencies: ["google-chart-container","google-chart-loader"],
    features: ["responsive", "interactive", "tooltip"],
    dataShape: `interface GoogleBarDatum {\n  label: string\n  value: number\n}`,
    snippet: `<GoogleBar data={data} color="#10b981" />`,
  },
  {
    id: "google-geochart",
    slug: "geochart",
    registryName: "google-geochart",
    title: "Google GeoChart Vector Map",
    description:
      "Interactive SVG choropleth world and country map with dynamic color scaling, regional hover tooltips, and click callbacks.",
    engine: "google",
    renderer: "google-runtime",
    status: "stable",
    difficulty: "intermediate",
    category: "geo",
    tags: ["google", "geo", "geochart", "map", "choropleth", "world"],
    componentPath: "registry/google/google-geochart.tsx",
    exportName: "GoogleGeoChart",
    dependencies: [],
    registryDependencies: ["google-chart-container","google-chart-loader"],
    features: ["responsive", "interactive", "tooltip", "selection"],
    dataShape: `interface GeoChartDatum {\n  region: string\n  value: number\n}`,
    snippet: `<GoogleGeoChart data={data} region="world" displayMode="regions" />`,
  },
] as const

export const legacyCharts: readonly ChartMetadata[] = [
  {
    id: "recharts-line-basic",
    slug: "line-basic",
    registryName: "line-basic",
    title: "Basic Line Chart",
    description:
      "Responsive single-series Cartesian line chart with pointer tooltips, smooth monotone curves, and keyboard exploration.",
    engine: "recharts",
    renderer: "svg",
    status: "stable",
    difficulty: "beginner",
    category: "line",
    tags: ["recharts", "line", "cartesian", "analytics", "trend"],
    componentPath: "registry/recharts/line-basic.tsx",
    exportName: "LineBasic",
    dependencies: ["recharts"],
    registryDependencies: ["chart-container","chart-state","chart-motion","chart-tooltip"],
    features: ["responsive", "animated", "interactive", "tooltip", "keyboard"],
    dataShape: `interface LineBasicDatum {\n  label: string\n  value: number\n}`,
    snippet: `<LineBasic data={data} color="var(--chart-1)" />`,
  },
  {
    id: "recharts-line-multiple",
    slug: "line-multiple",
    registryName: "line-multiple",
    title: "Multi-Series Line Chart",
    description:
      "Multi-series line chart supporting comparisons between primary and secondary metrics with solid and dashed strokes and shared tooltips.",
    engine: "recharts",
    renderer: "svg",
    status: "stable",
    difficulty: "beginner",
    category: "line",
    tags: ["recharts", "line", "multi-series", "comparison", "trends"],
    componentPath: "registry/recharts/line-multiple.tsx",
    exportName: "LineMultiple",
    dependencies: ["recharts"],
    registryDependencies: ["chart-container","chart-tooltip"],
    features: ["responsive", "interactive", "tooltip", "legend", "keyboard"],
    dataShape: `interface MultiSeriesDatum {\n  label: string\n  current: number\n  previous: number\n}`,
    snippet: `<LineMultiple data={data} />`,
  },
  {
    id: "recharts-area-basic",
    slug: "area-basic",
    registryName: "area-basic",
    title: "Basic Area Chart",
    description:
      "Filled gradient area chart designed for continuous volume, cumulative metrics, and bandwidth visualization with a subtle vertical gradient.",
    engine: "recharts",
    renderer: "svg",
    status: "stable",
    difficulty: "beginner",
    category: "area",
    tags: ["recharts", "area", "gradient", "volume", "metrics"],
    componentPath: "registry/recharts/area-basic.tsx",
    exportName: "AreaBasic",
    dependencies: ["recharts"],
    registryDependencies: ["chart-container","chart-tooltip"],
    features: ["responsive", "animated", "interactive", "tooltip", "keyboard"],
    dataShape: `interface AreaBasicDatum {\n  label: string\n  value: number\n}`,
    snippet: `<AreaBasic data={data} color="var(--chart-1)" />`,
  },
  {
    id: "recharts-bar-basic",
    slug: "bar-basic",
    registryName: "bar-basic",
    title: "Basic Bar Chart",
    description:
      "Discrete category comparison bar chart with rounded tops, responsive bar widths, and subtle background tracks.",
    engine: "recharts",
    renderer: "svg",
    status: "stable",
    difficulty: "beginner",
    category: "bar",
    tags: ["recharts", "bar", "column", "comparison", "discrete"],
    componentPath: "registry/recharts/bar-basic.tsx",
    exportName: "BarBasic",
    dependencies: ["recharts"],
    registryDependencies: ["chart-container","chart-motion","chart-tooltip"],
    features: ["responsive", "animated", "interactive", "tooltip", "keyboard"],
    dataShape: `interface BarBasicDatum {\n  label: string\n  value: number\n}`,
    snippet: `<BarBasic data={data} color="var(--chart-1)" />`,
  },
]

export function getAllCharts(): readonly ChartMetadata[] {
  return charts
}

export function getChartsByEngine(
  engine: ChartMetadata["engine"]
): readonly ChartMetadata[] {
  return charts.filter((c) => c.engine === engine)
}

export function getChartByEngineAndSlug(
  engine: string,
  slug: string
): ChartMetadata | undefined {
  return (
    charts.find((c) => c.engine === engine && c.slug === slug) ||
    legacyCharts.find((c) => c.engine === engine && c.slug === slug)
  )
}

export function getChartById(id: string): ChartMetadata | undefined {
  return (
    charts.find((c) => c.id === id || c.registryName === id || c.slug === id) ||
    legacyCharts.find((c) => c.id === id || c.registryName === id || c.slug === id)
  )
}
