"use client"
import { useState, type ReactNode } from "react"
import { useSearchParams } from "next/navigation"
import Link from "next/link"
import Image from "next/image"
import { HugeiconsIcon } from "@hugeicons/react"
import { RefreshIcon, Settings01Icon } from "@hugeicons/core-free-icons"
import { getChartById } from "@/config/charts"
import { playgroundIds,isPlaygroundId,playgroundDefaults,playgroundFixture,validatePlaygroundData,generatePlaygroundUsage,type PlaygroundId,type PlaygroundSettings } from "@/lib/playground/model"
import { PreviewWorkspace } from "@/components/preview/preview-workspace"
import { ChartPreviewBoundary } from "@/components/chart-gallery/chart-renderer"
import { ChartInstall } from "@/components/chart-detail/chart-install"
import { LiveCodeBlock } from "@/components/docs/live-code-block"
import { PlaygroundChart } from "./playground-chart"
import { PlaygroundDataEditor } from "./playground-data-editor"
import { Button } from "@/components/ui/button"
import { Select,SelectTrigger,SelectValue,SelectContent,SelectItem } from "@/components/ui/select"
import { Tabs,TabsList,TabsTrigger,TabsContent } from "@/components/ui/tabs"
import { Sheet,SheetTrigger,SheetContent,SheetHeader,SheetTitle,SheetDescription } from "@/components/ui/sheet"
function Workbench({id,source}:{id:PlaygroundId;source:ReactNode}) {
  const chart=getChartById(id)!
  const [settings,setSettings]=useState(()=>playgroundDefaults(id))
  const [data,setData]=useState(()=>playgroundFixture(id))
  const [draft,setDraft]=useState(()=>JSON.stringify(playgroundFixture(id),null,2))
  const [error,setError]=useState<string>()
  function update(patch:Partial<PlaygroundSettings>){setSettings(s=>({...s,...patch}))}
  function edit(text:string){setDraft(text);const result=validatePlaygroundData(text,id);setError(result.error);if(result.data)setData(result.data)}
  const categorical=id!=="d3-animated-line",cartesian=id==="line-basic"||id==="bar-basic"
  const selectControl=(key:"curve"|"grid"|"palette",label:string,options:string[]) => <label className="workbench-control">{label}<Select value={settings[key]} onValueChange={value=>{if(value)update({[key]:value})}}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(value=><SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectContent></Select></label>
  const toggle=(key:"showXAxis"|"showYAxis"|"tooltip"|"legend"|"motion"|"reducedMotion",label:string) => <label className="workbench-toggle"><span>{label}</span><input type="checkbox" checked={settings[key]} onChange={e=>update({[key]:e.target.checked})}/></label>
  const range=(key:"height"|"width"|"innerRadius"|"duration",label:string,min:number,max:number,step=1) => <label className="workbench-range"><span>{label}<output>{settings[key]}{key==="duration"?"s":key==="innerRadius"?"%":"px"}</output></span><input aria-label={label} type="range" min={min} max={max} step={step} value={settings[key]} onChange={e=>update({[key]:Number(e.target.value)})}/></label>
  const controls=<div className="workbench-controls"><fieldset><legend>Appearance</legend>{selectControl("palette","Palette",["default","mono"])}{(id==="line-basic"||!categorical)&&selectControl("curve","Curve",["linear","monotone","step"])}{id==="donut-basic"&&range("innerRadius","Inner radius",0,80)}</fieldset>{(cartesian||!categorical)&&<fieldset><legend>Axes & grid</legend>{cartesian&&<>{toggle("showXAxis","X axis")}{toggle("showYAxis","Y axis")}</>}{selectControl("grid","Grid",cartesian?["off","horizontal","both"]:["off","horizontal"])}</fieldset>}{categorical&&<fieldset><legend>Interaction</legend>{toggle("tooltip","Tooltip")}{toggle("legend","Legend")}{id==="line-basic"&&<p>Single-series legend is hidden by default.</p>}</fieldset>}<fieldset><legend>Motion</legend>{toggle("motion","Animation")}{settings.motion&&range("duration","Duration",.1,2,.1)}{toggle("reducedMotion","Simulate reduced motion")}</fieldset><fieldset><legend>Layout</legend>{range("width","Container width",280,1400,10)}{range("height","Chart height",180,600,10)}</fieldset><Button variant="outline" onClick={()=>setSettings(playgroundDefaults(id))}><HugeiconsIcon icon={RefreshIcon} size={15}/>Reset configuration</Button></div>
  return <><div className="workbench-grid"><aside className="workbench-inspector"><div className="workbench-inspector-heading"><HugeiconsIcon icon={Settings01Icon} size={16}/>Configuration</div>{controls}</aside><div className="workbench-stage"><div className="workbench-stage-heading"><span>{chart.title}</span><span className="lens-eyebrow">{chart.engine} / SVG</span></div><PreviewWorkspace title={chart.title} width={settings.width} onWidthChange={width=>update({width})} height={settings.height} theme={settings.theme} onThemeChange={theme=>update({theme})} palette={settings.palette} reducedMotion={settings.reducedMotion} animate={settings.motion} inspector={({width,reducedMotion})=>`${chart.engine.toUpperCase()} / SVG / ${width} × ${settings.height} / ${width<480?"COMPACT":width<768?"MEDIUM":"WIDE"} / ${data.length} POINTS / MOTION ${settings.motion&&!reducedMotion?"ON":"OFF"}`}>{({width,reducedMotion,iteration})=><ChartPreviewBoundary key={id}><PlaygroundChart key={iteration} id={id} settings={settings} data={data} width={width} reducedMotion={reducedMotion}/></ChartPreviewBoundary>}</PreviewWorkspace>{error&&<p className="workbench-safe-note">Last valid data shown. Review the editor diagnostic below.</p>}<div className="workbench-mobile-config"><Sheet><SheetTrigger render={<Button variant="outline"/>}><HugeiconsIcon icon={Settings01Icon} size={16}/>Configure chart</SheetTrigger><SheetContent className="charts-surface workbench-sheet" data-theme="dark"><SheetHeader><SheetTitle>Configure {chart.title}</SheetTitle><SheetDescription>Only controls supported by this chart are shown.</SheetDescription></SheetHeader>{controls}</SheetContent></Sheet></div><div className="workbench-source"><Tabs defaultValue="usage"><TabsList variant="line" aria-label="Playground source"><TabsTrigger value="usage">Usage</TabsTrigger><TabsTrigger value="data">Data</TabsTrigger><TabsTrigger value="component">Component</TabsTrigger></TabsList><TabsContent value="usage"><LiveCodeBlock code={generatePlaygroundUsage(id,settings,data)}/></TabsContent><TabsContent value="data"><LiveCodeBlock code={JSON.stringify(data,null,2)} language="json" title="Last valid data"/></TabsContent><TabsContent value="component">{source}</TabsContent></Tabs></div></div></div><PlaygroundDataEditor id={id} draft={draft} onDraftChange={edit} error={error} onReset={()=>edit(JSON.stringify(playgroundFixture(id),null,2))}/><ChartInstall registryName={id}/><p className="workbench-own">Need more control? <Link href={`/charts/${chart.engine}/${chart.slug}`}>Inspect the chart</Link>, install its source, and edit it directly.</p></>
}
export function PlaygroundShell({sources}:{sources:Record<string,ReactNode>}) {
  const params=useSearchParams(),query=params.get("chart"),id=isPlaygroundId(query)?query:"line-basic"
  return <main id="main" tabIndex={-1} className="lens-shell product-shell"><header className="product-heading"><div><span className="lens-eyebrow">PLOTCN / PLAYGROUND</span><h1>A chart. Your controls.</h1><p>Change the data, inspect the behavior, take the source.</p></div><div className="workbench-selector"><Image src={`/brand/engines/${id.startsWith("d3")?"d3":"recharts"}.svg`} width={28} height={24} alt=""/><Select value={id} onValueChange={value=>{if(value&&isPlaygroundId(value))window.history.pushState(null,"",`/playground?chart=${value}`)}}><SelectTrigger aria-label="Choose chart"><SelectValue/></SelectTrigger><SelectContent>{playgroundIds.map(chart=><SelectItem key={chart} value={chart}>{getChartById(chart)!.title}</SelectItem>)}</SelectContent></Select></div></header>{query&&!isPlaygroundId(query)&&<p role="status">This chart is not available in the Playground. Showing Basic Line Chart.</p>}<Workbench key={id} id={id} source={sources[id]}/></main>
}
