import { readFileSync, writeFileSync } from "node:fs"
const root = new URL("../", import.meta.url)
const source = readFileSync(new URL("src/components/brand/AppLogo.tsx", root), "utf8")
const paths = [...source.matchAll(/<path fill="currentColor" d="([^"]+)"/g)].map((match) => match[1])
if (paths.length !== 3) throw new Error("Expected three canonical logo paths")
const svg = (color, background = false) => `<!-- Generated by scripts/sync-brand.mjs; edit AppLogo.tsx. -->\n<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" fill="none">\n${background ? '  <rect width="32" height="32" rx="7" fill="#09090B" />\n' : ""}${paths.map((d) => `  <path fill="${color}" d="${d}" />`).join("\n")}\n</svg>\n`
const assets = {
  "public/brand/plotcn-logo.svg": svg("currentColor"),
  "public/brand/plotcn-mark.svg": svg("currentColor"),
  "public/brand/plotcn-mark-dark.svg": svg("#FAFAFA"),
  "public/brand/plotcn-mark-light.svg": svg("#09090B"),
  "app/icon.svg": svg("#FAFAFA", true),
  "src/app/icon.svg": svg("#FAFAFA", true),
}
for (const [path, content] of Object.entries(assets)) {
  const file = new URL(path, root)
  if (process.argv.includes("--check")) {
    if (readFileSync(file, "utf8") !== content) throw new Error(`Stale brand asset: ${path}`)
  } else writeFileSync(file, content)
}

const png=await (await import('sharp')).default(readFileSync(new URL('app/icon.svg', root))).resize(32,32).png().toBuffer()
const header=Buffer.alloc(22)
header.writeUInt16LE(1,2);header.writeUInt16LE(1,4);header[6]=32;header[7]=32
header.writeUInt16LE(1,10);header.writeUInt16LE(32,12);header.writeUInt32LE(png.length,14);header.writeUInt32LE(22,18)
const icoFile = new URL('app/favicon.ico', root)
const icoContent = Buffer.concat([header,png])
if (process.argv.includes('--check')) {
  if (!readFileSync(icoFile).equals(icoContent)) throw new Error('Stale favicon.ico')
} else writeFileSync(icoFile, icoContent)
