import type { ChartDetailDoc } from "./types"

export const lineRangeDoc: ChartDetailDoc = {
  chartId: "recharts-line-range",
  engine: "recharts",
  category: "line",
  renderer: "svg",
  status: "preview",
  blueprint: "RECHARTS / LINE / RANGE / PREVIEW",

  quickFacts: {
    bestFor: "Demand forecasts with confidence intervals, sensor telemetry with tolerance envelopes, SLA normal operating bands, or statistical prediction intervals.",
    dataModel: "Readonly array of observations with a shared horizontal domain, central trend observation, and paired lower/upper limits.",
    interaction: "Synchronized nearest-X vertical crosshair, central active point, and structured interval tooltip displaying central value and lower–upper limits.",
    responsive: "Unified Y-scale encompassing central line and envelope limits; automatic X-axis tick thinning; zero container clipping.",
    animation: "Coordinated interval and line reveal (350ms ease-out); automatically disabled under prefers-reduced-motion.",
    runtime: "Recharts ComposedChart combining Area (interval) and Line (central) in SVG (source-owned, zero Plotcn runtime packages).",
  },

  dataFormat: {
    summary: "Accepts a readonly array of objects containing a horizontal coordinate and three numeric metrics: central trend, lower boundary, and upper boundary.",
    fields: [
      {
        field: "xKey",
        type: "string | number | Date",
        required: true,
        description: "Horizontal domain coordinate representing time, period, or an ordered discrete category.",
      },
      {
        field: "valueKey",
        type: "number | null | undefined",
        required: true,
        description: "Central numeric observation (e.g. forecast, mean, or actual value). Rendered as the prominent solid stroke.",
      },
      {
        field: "lowerKey",
        type: "number | null | undefined",
        required: true,
        description: "Lower limit of the interval envelope (e.g. 5th percentile, minimum tolerance, or -2σ limit).",
      },
      {
        field: "upperKey",
        type: "number | null | undefined",
        required: true,
        description: "Upper limit of the interval envelope (e.g. 95th percentile, maximum tolerance, or +2σ limit).",
      },
    ],
    nullPolicy: "Truthful gap policy: missing bounds leave an explicit gap in the band without fabricating values. Missing central points preserve valid range bands.",
    orderingPolicy: "Caller must supply observations in ascending chronological or ordinal sequence.",
    exampleRows: [
      { month: "Jan", forecast: 120, lower: 105, upper: 138 },
      { month: "Feb", forecast: 135, lower: 118, upper: 152 },
      { month: "Mar", forecast: 150, lower: 125, upper: 175 },
      { month: "Apr", forecast: 142, lower: 115, upper: 168 },
      { month: "May", forecast: 168, lower: 132, upper: 204 },
      { month: "Jun", forecast: 185, lower: 145, upper: 225 },
    ],
  },

  props: [
    {
      name: "data",
      type: "readonly TData[]",
      default: "[]",
      required: true,
      category: "core",
      description: "Readonly array of structured observation records. Caller data is never mutated.",
      bestFor: "Primary dataset",
    },
    {
      name: "xKey",
      type: "keyof TData & string",
      default: "—",
      required: true,
      category: "core",
      description: "Property name for the horizontal X-axis domain (e.g. date, month, or sprint).",
      bestFor: "Domain coordinates",
    },
    {
      name: "valueKey",
      type: "keyof TData & string",
      default: '"value"',
      required: false,
      category: "core",
      description: "Field name for the central observation value plotted with dominant solid stroke.",
      bestFor: "Central signal series",
    },
    {
      name: "lowerKey",
      type: "keyof TData & string",
      default: '"lower"',
      required: false,
      category: "core",
      description: "Field name for the lower limit of the range band.",
      bestFor: "Lower interval limit",
    },
    {
      name: "upperKey",
      type: "keyof TData & string",
      default: '"upper"',
      required: false,
      category: "core",
      description: "Field name for the upper limit of the range band.",
      bestFor: "Upper interval limit",
    },
    {
      name: "series",
      type: "RangeLineSeriesConfig<TData>",
      default: "undefined",
      required: false,
      category: "core",
      description: "Optional range-aware series descriptor combining valueKey, lowerKey, upperKey, and semantic labels.",
      bestFor: "Encapsulated series config",
    },
    {
      name: "label",
      type: "string",
      default: '"Central"',
      required: false,
      category: "visual",
      description: "Human-readable label for the central series displayed in tooltips and legends.",
      bestFor: "Series identification",
    },
    {
      name: "rangeLabel",
      type: "string",
      default: '"Range"',
      required: false,
      category: "visual",
      description: "Human-readable label for the interval envelope (e.g. 'Confidence Interval', 'Operating Range').",
      bestFor: "Interval identification",
    },
    {
      name: "color",
      type: "string",
      default: '"var(--chart-1, #10b981)"',
      required: false,
      category: "visual",
      description: "Primary theme stroke color for the central line. Accepts CSS variables or color values.",
      bestFor: "Primary brand theme",
      previewable: true,
      controlType: "segmented",
      controlOptions: [
        { value: "var(--chart-1, #10b981)", label: "Emerald" },
        { value: "#0ea5e9", label: "Sky" },
        { value: "#8b5cf6", label: "Purple" },
        { value: "#f59e0b", label: "Amber" },
      ],
    },
    {
      name: "rangeOpacity",
      type: "number",
      default: "0.18",
      required: false,
      category: "visual",
      description: "Fill opacity applied to the range envelope band (0 to 1).",
      bestFor: "Interval emphasis",
      previewable: true,
      controlType: "segmented",
      controlOptions: [
        { value: 0.1, label: "Subtle (10%)" },
        { value: 0.18, label: "Default (18%)" },
        { value: 0.32, label: "Strong (32%)" },
      ],
    },
    {
      name: "showRangeBoundary",
      type: "boolean",
      default: "false",
      required: false,
      category: "visual",
      description: "Whether to render subtle dashed boundary strokes along the upper and lower limits of the band.",
      bestFor: "Boundary clarity",
      previewable: true,
      controlType: "segmented",
      controlOptions: [
        { value: false, label: "Boundary Off" },
        { value: true, label: "Boundary On" },
      ],
    },
    {
      name: "curve",
      type: '"monotone" | "linear" | "step"',
      default: '"monotone"',
      required: false,
      category: "visual",
      description: "Geometric curve interpolation applied synchronously to both the central line and the range band.",
      bestFor: "Interpolation style",
      previewable: true,
      controlType: "segmented",
      controlOptions: [
        { value: "monotone", label: "Monotone" },
        { value: "linear", label: "Linear" },
        { value: "step", label: "Step" },
      ],
    },
    {
      name: "height",
      type: "number | string",
      default: "340",
      required: false,
      category: "core",
      description: "Container height in pixels or standard CSS dimension strings.",
      bestFor: "Dashboard slot sizing",
      previewable: true,
      controlType: "segmented",
      controlOptions: [
        { value: 260, label: "Compact (260px)" },
        { value: 340, label: "Default (340px)" },
        { value: 420, label: "Spacious (420px)" },
      ],
    },
    {
      name: "showLegend",
      type: "boolean",
      default: "false",
      required: false,
      category: "visual",
      description: "Whether to display the chart legend distinguishing central line from range band.",
      bestFor: "Multi-series clarity",
      previewable: true,
      controlType: "segmented",
      controlOptions: [
        { value: false, label: "Legend Off" },
        { value: true, label: "Legend On" },
      ],
    },
    {
      name: "showGrid",
      type: "boolean",
      default: "true",
      required: false,
      category: "visual",
      description: "Whether to render subtle horizontal background reference gridlines.",
      bestFor: "Grid density control",
      previewable: true,
      controlType: "segmented",
      controlOptions: [
        { value: true, label: "Grid On" },
        { value: false, label: "Grid Off" },
      ],
    },
    {
      name: "showRangeWidthInTooltip",
      type: "boolean",
      default: "false",
      required: false,
      category: "interaction",
      description: "Whether to calculate and display the derived range span (upper - lower) in the tooltip.",
      bestFor: "Quantitative interval inspection",
    },
    {
      name: "missingValuePolicy",
      type: '"gap" | "connect"',
      default: '"gap"',
      required: false,
      category: "core",
      description: "Handling of null observations in the central line. 'gap' preserves visual breaks; 'connect' bridges adjacent points.",
      bestFor: "Data safety & truthful representation",
    },
    {
      name: "domain",
      type: '[number, number] | ["auto", "auto"]',
      default: '"auto"',
      required: false,
      category: "core",
      description: "Explicit Y-axis numeric domain spanning both central and range values, or 'auto' unified scale calculation.",
    },
    {
      name: "showXAxis",
      type: "boolean",
      default: "true",
      required: false,
      category: "visual",
      description: "Whether to display the horizontal X-axis tick labels.",
    },
    {
      name: "showYAxis",
      type: "boolean",
      default: "true",
      required: false,
      category: "visual",
      description: "Whether to display the unified vertical Y-axis scale.",
    },
    {
      name: "motion",
      type: "boolean | { duration?: number }",
      default: "true",
      required: false,
      category: "visual",
      description: "Synchronized reveal animation (350ms). Automatically disabled under prefers-reduced-motion.",
    },
    {
      name: "title",
      type: "string",
      default: '"Range Line Chart"',
      required: false,
      category: "a11y",
      description: "Accessible name announced to screen-readers for the chart figure region.",
    },
    {
      name: "description",
      type: "string",
      default: "undefined",
      required: false,
      category: "a11y",
      description: "Long-form context describing what the trend and interval envelope communicate.",
    },
    {
      name: "loading",
      type: "boolean",
      default: "false",
      required: false,
      category: "advanced",
      description: "Renders a neutral loading skeleton preserving container footprint without fake bands.",
    },
    {
      name: "error",
      type: "Error | string | null",
      default: "null",
      required: false,
      category: "advanced",
      description: "Renders an actionable error state banner with optional retry trigger.",
    },
    {
      name: "unavailable",
      type: "boolean | string | null",
      default: "false",
      required: false,
      category: "advanced",
      description: "Renders a metric unavailability notice (e.g. permission restriction or missing interval model).",
    },
  ],

  examples: [
    {
      id: "forecast-envelope",
      title: "Demand Forecast with Confidence Band",
      description: "Expected monthly product demand with a widening 95% statistical confidence envelope.",
      snippet: `<RangeLine data={forecastData} xKey="month" valueKey="forecast" lowerKey="lower" upperKey="upper" label="Forecast" rangeLabel="95% Confidence" />`,
      props: { label: "Forecast", rangeLabel: "95% Confidence", height: 260 },
    },
    {
      id: "tolerance-band",
      title: "API Latency with Operating Envelope",
      description: "Observed p95 latency curve plotted inside contractually acceptable SLA bounds with boundary strokes.",
      snippet: `<RangeLine data={latencyData} xKey="time" valueKey="latency" lowerKey="slaMin" upperKey="slaMax" label="Observed" rangeLabel="SLA Envelope" showRangeBoundary color="#0ea5e9" />`,
      props: { label: "Observed", rangeLabel: "SLA Envelope", showRangeBoundary: true, color: "#0ea5e9", height: 260 },
    },
    {
      id: "step-capacity",
      title: "Tiered Capacity Allocation Band",
      description: "Scheduled infrastructure provision tiers with discrete step interpolation on both signal and limits.",
      snippet: `<RangeLine data={capacityData} xKey="hour" valueKey="allocated" lowerKey="minCap" upperKey="maxCap" curve="step" label="Allocated" rangeLabel="Provisioned" color="#8b5cf6" />`,
      props: { curve: "step", label: "Allocated", rangeLabel: "Provisioned", color: "#8b5cf6", height: 260 },
    },
    {
      id: "compact-widget",
      title: "Compact Metric Overview Widget",
      description: "Condensed 200px dashboard tile with hidden axes, maintaining interval visibility in tight slots.",
      snippet: `<RangeLine data={summaryData} xKey="week" valueKey="mrr" lowerKey="targetMin" upperKey="targetMax" showYAxis={false} height={200} />`,
      props: { showYAxis: false, color: "#10b981", height: 200 },
    },
  ],

  responsive: {
    overview: "Range Line scales the central line and interval band synchronously across container widths. The unified Y-domain recalculates to comfortably enclose extreme bounds without clipping.",
    breakpoints: [
      { name: "Desktop", width: ">= 1024px", behavior: "Full interval tooltip with exact lower and upper values, optional range span, and clear line-versus-band distinction." },
      { name: "Tablet", width: "640px - 1023px", behavior: "Thinned X-axis labels, preserved band continuity, compact margins, tooltip pinned within viewport boundaries." },
      { name: "Mobile", width: "< 640px", behavior: "Edge-to-edge scrub inspection, preserved interval visibility without opacity blowout, touch-first scrub interaction." },
    ],
  },

  animation: {
    overview: "Central line and interval band reveal synchronously on initial mount (350ms). Theme switches, container resize, and prop changes transition smoothly without geometry flicker.",
    duration: "350ms ease-out",
    refreshable: true,
  },

  interaction: {
    tooltip: "Plotcn interval tooltip displaying central observation value and lower – upper range limits with configured semantic labels.",
    crosshair: "Vertical dashed guideline intersecting both the central active point and the interval envelope.",
    legend: "Interactive legend highlighting central line (solid line) and range envelope (filled rectangle) semantics.",
  },

  accessibility: {
    role: "region",
    summary: "Screen-reader figure region with quantitative interval summary (observation count, central range, and interval availability).",
    screenReader: "VoiceOver and NVDA announce central values and lower–upper limits without SVG node traversal.",
    keyboardShortcuts: [
      { key: "Tab", action: "Focus range chart region with prominent focus ring" },
      { key: "ArrowLeft", action: "Step to previous observation and announce central + range values" },
      { key: "ArrowRight", action: "Step to next observation and announce central + range values" },
      { key: "Home", action: "Jump to first observation point" },
      { key: "End", action: "Jump to latest observation point" },
      { key: "Escape", action: "Clear active inspection state" },
    ],
    colorIndependence: "Central observation is a prominent solid line (2px) while the interval is an area band (fill with optional dashed boundary strokes), providing clear geometric differentiation independent of color.",
    reducedMotion: "Automatically suppresses stroke draw and area reveal animations when user requests reduced motion.",
  },

  sourceAnatomy: {
    tree: {
      name: "RangeLine",
      role: "Root figure wrapper",
      description: "Provides keyboard navigation, accessible interval summary, and responsive boundaries.",
      children: [
        {
          name: "ChartContainer",
          role: "CSS token bridge",
          description: "Scoped CSS variables for axes, grid, and crosshairs without global pollution.",
          children: [
            {
              name: "ResponsiveContainer",
              role: "Auto-sizing viewport",
              description: "Recharts container measuring width and height via ResizeObserver.",
              children: [
                { name: "ComposedChart", role: "SVG coordinator", description: "Calculates shared unified coordinate scale across Area and Line." },
                { name: "CartesianGrid", role: "Reference structure", description: "Subtle dashed horizontal dividers." },
                { name: "XAxis / YAxis", role: "Coordinate scales", description: "Single honest Y scale spanning central and extreme range limits." },
                { name: "Tooltip (RangeTooltipContent)", role: "Interval inspector", description: "Card displaying central value and lower – upper range boundaries." },
                { name: "Area (Range Envelope)", role: "Interval band", description: "Rendered between lower and upper limits using [lower, upper] tuple." },
                { name: "Line (Central Signal)", role: "Dominant trend", description: "Solid stroke with active point marker at inspected X." },
                { name: "Legend (RangeLegendContent)", role: "Visual key", description: "Distinguishes central line vs filled band semantics." },
              ],
            },
          ],
        },
      ],
    },
    sourceFiles: [
      { path: "components/charts/recharts/line-range.tsx", description: "Primary RangeLine interval visualization component" },
      { path: "components/charts/shared/chart-container.tsx", description: "CSS variable token bridge and container wrapper" },
      { path: "components/charts/shared/chart-state.tsx", description: "Loading, empty, and error fallback states" },
      { path: "components/charts/shared/use-chart-reduced-motion.ts", description: "prefers-reduced-motion media query hook" },
    ],
    registryDependencies: ["chart-container", "chart-state", "use-chart-reduced-motion"],
    npmDependencies: ["recharts"],
  },
}
