import type { ChartDetailDoc } from "./types"

export const lineSignalDoc: ChartDetailDoc = {
  chartId: "recharts-line-signal",
  engine: "recharts",
  category: "line",
  renderer: "svg",
  status: "stable",
  blueprint: "Focused single-series time-series line visualization with restrained active-point emphasis.",

  quickFacts: {
    bestFor: "Single dominant metric over ordered time or category (revenue, latency, API traffic, conversion)",
    dataModel: "Readonly array of observations with an X-domain key and one numeric series",
    interaction: "Nearest-X crosshair, active point marker, tabular tooltip, Left/Right arrow navigation",
    responsive: "Container-aware ResizeObserver, adaptive X tick density, zero horizontal overflow",
    animation: "Restrained line reveal (350ms ease-out), respects prefers-reduced-motion",
    runtime: "Recharts SVG (source owned, zero Plotcn runtime packages)",
  },

  dataFormat: {
    summary: "Accepts a readonly array of objects containing a chronological or ordered categorical X key and a numeric series value.",
    fields: [
      {
        field: "xKey",
        type: "string | number | Date",
        required: true,
        description: "Horizontal coordinate representing time or an ordered discrete category.",
      },
      {
        field: "seriesKey",
        type: "number | null | undefined",
        required: true,
        description: "Primary numeric observation. Missing observations (null/undefined) remain gaps by default.",
      },
    ],
    nullPolicy: "Truthful gap policy: null and undefined values produce a break in the curve and are never coerced to zero.",
    orderingPolicy: "Caller must supply observations in ascending chronological or ordinal sequence.",
    exampleRows: [
      { date: "2026-03-01", latency: 42 },
      { date: "2026-03-02", latency: 38 },
      { date: "2026-03-03", latency: 55 },
      { date: "2026-03-04", latency: null },
      { date: "2026-03-05", latency: 48 },
      { date: "2026-03-06", latency: 62 },
      { date: "2026-03-07", latency: 51 },
    ],
  },

  props: [
    {
      name: "data",
      type: "readonly TData[]",
      default: "[]",
      required: true,
      category: "core",
      description: "Readonly array of observation records. Will not be mutated by the component.",
      bestFor: "Primary dataset",
    },
    {
      name: "xKey",
      type: "keyof TData & string",
      default: "—",
      required: true,
      category: "core",
      description: "Field name for the horizontal axis domain (e.g. date, timestamp, or step).",
      bestFor: "Domain mapping",
    },
    {
      name: "seriesKey",
      type: "keyof TData & string",
      default: '"value"',
      required: false,
      category: "core",
      description: "Direct field name for the numeric value to plot.",
      bestFor: "Single series lookup",
    },
    {
      name: "curve",
      type: '"monotone" | "linear" | "step"',
      default: '"monotone"',
      required: false,
      category: "visual",
      description: "Interpolation strategy between points. Monotone is ideal for smooth rates; step for discrete state shifts.",
      bestFor: "Visual curve style",
      previewable: true,
      controlType: "segmented",
      controlOptions: [
        { value: "monotone", label: "Monotone" },
        { value: "linear", label: "Linear" },
        { value: "step", label: "Step" },
      ],
    },
    {
      name: "color",
      type: "string",
      default: '"var(--chart-1, #10b981)"',
      required: false,
      category: "visual",
      description: "Primary line stroke color. Accepts any CSS variable token or hex string.",
      bestFor: "Theming & brand identity",
      previewable: true,
      controlType: "segmented",
      controlOptions: [
        { value: "var(--chart-1, #10b981)", label: "Emerald" },
        { value: "#0ea5e9", label: "Sky" },
        { value: "#8b5cf6", label: "Purple" },
        { value: "#f59e0b", label: "Amber" },
      ],
    },
    {
      name: "height",
      type: "number | string",
      default: "320",
      required: false,
      category: "core",
      description: "Container height in pixels or standard CSS dimension strings.",
      bestFor: "Dashboard slot sizing",
      previewable: true,
      controlType: "segmented",
      controlOptions: [
        { value: 240, label: "Compact (240px)" },
        { value: 320, label: "Default (320px)" },
        { value: 400, label: "Tall (400px)" },
      ],
    },
    {
      name: "showGrid",
      type: "boolean",
      default: "true",
      required: false,
      category: "visual",
      description: "Whether to render subtle horizontal background reference gridlines.",
      bestFor: "Grid density control",
      previewable: true,
      controlType: "segmented",
      controlOptions: [
        { value: true, label: "Grid On" },
        { value: false, label: "Grid Off" },
      ],
    },
    {
      name: "missingValuePolicy",
      type: '"gap" | "connect"',
      default: '"gap"',
      required: false,
      category: "core",
      description: "Handling of null or undefined observations. 'gap' preserves visual breaks; 'connect' bridges adjacent points.",
      bestFor: "Data safety & truthful representation",
      previewable: true,
      controlType: "segmented",
      controlOptions: [
        { value: "gap", label: "Gap (Truthful)" },
        { value: "connect", label: "Connect" },
      ],
    },
    {
      name: "tickStrategy",
      type: '"auto" | "all" | "preserve-start" | "preserve-end" | "preserve-both"',
      default: '"auto"',
      required: false,
      category: "core",
      description: "X-axis tick density calculation to prevent label collision on narrow containers.",
    },
    {
      name: "showXAxis",
      type: "boolean",
      default: "true",
      required: false,
      category: "visual",
      description: "Whether to display the horizontal axis tick labels.",
    },
    {
      name: "showYAxis",
      type: "boolean",
      default: "true",
      required: false,
      category: "visual",
      description: "Whether to display the vertical axis metric values.",
    },
    {
      name: "showLegend",
      type: "boolean",
      default: "false",
      required: false,
      category: "visual",
      description: "Whether to display a chart legend. Hidden by default for focused single-series clarity.",
    },
    {
      name: "motion",
      type: "boolean | { duration?: number }",
      default: "true",
      required: false,
      category: "visual",
      description: "Initial line draw animation. Automatically disabled when prefers-reduced-motion is active.",
    },
    {
      name: "title",
      type: "string",
      default: '"Signal Line"',
      required: false,
      category: "a11y",
      description: "Accessible name announced to screen-readers for the chart region.",
    },
    {
      name: "description",
      type: "string",
      default: "undefined",
      required: false,
      category: "a11y",
      description: "Long-form context describing what the metric trend communicates.",
    },
    {
      name: "loading",
      type: "boolean",
      default: "false",
      required: false,
      category: "advanced",
      description: "Renders a neutral loading skeleton preserving container footprint without fake data.",
    },
    {
      name: "error",
      type: "Error | string | null",
      default: "null",
      required: false,
      category: "advanced",
      description: "Renders an actionable error state banner with optional retry trigger.",
    },
    {
      name: "unavailable",
      type: "boolean | string | null",
      default: "false",
      required: false,
      category: "advanced",
      description: "Renders a metric unavailability notice (e.g. permission restriction or retention limit).",
    },
  ],

  examples: [
    {
      id: "basic-signal",
      title: "Daily Server Latency",
      description: "Standard single-series monitoring metric with monotone smoothing and active crosshair.",
      snippet: `<SignalLine data={latencyData} xKey="time" seriesKey="ms" color="var(--chart-1)" />`,
      props: { height: 260 },
    },
    {
      id: "missing-data",
      title: "Truthful Data Gap",
      description: "Missing telemetry observations rendered with explicit visual gaps instead of coercing to zero.",
      snippet: `<SignalLine data={downtimeData} xKey="hour" seriesKey="requests" missingValuePolicy="gap" />`,
      props: { missingValuePolicy: "gap", height: 260 },
    },
    {
      id: "step-interpolation",
      title: "Concurrency Limit Changes",
      description: "Discrete step curve illustrating instantaneous state transitions.",
      snippet: `<SignalLine data={capacityData} xKey="date" seriesKey="slots" curve="step" color="#0ea5e9" />`,
      props: { curve: "step", color: "#0ea5e9", height: 260 },
    },
    {
      id: "compact-dashboard",
      title: "Compact Card Trend",
      description: "Condensed 180px trend view without Y-axis clutter for dashboard overview tiles.",
      snippet: `<SignalLine data={metricData} xKey="day" seriesKey="value" showYAxis={false} height={180} />`,
      props: { showYAxis: false, height: 180 },
    },
  ],

  responsive: {
    overview: "Signal Line leverages container ResizeObserver measurements to dynamically reduce X-axis tick frequency, preserving legible typography down to 320px containers.",
    breakpoints: [
      { name: "Desktop (1024px+)", width: ">= 1024px", behavior: "Full tick density, spacious margins, detailed tooltips" },
      { name: "Tablet (640px - 1023px)", width: "640px - 1023px", behavior: "Thinned X-axis labels, preserved line continuity, compact margins" },
      { name: "Mobile (< 640px)", width: "< 640px", behavior: "Aggressive tick thinning, touch scrub target, negative margin compensation" },
    ],
  },

  animation: {
    overview: "Smooth 350ms path stroke reveal on first mount. Window resize, live data updates, and theme switches bypass geometry resets to avoid visual flicker.",
    duration: "350ms ease-out",
    refreshable: true,
  },

  interaction: {
    tooltip: "Plotcn glassmorphic tooltip with monospace tabular numbers, label formatting, and high-contrast border.",
    crosshair: "Vertical dashed stroke tracking pointer across the X-axis for nearest-point inspection.",
    legend: "Hidden by default to maximize vertical plot room for the primary series.",
  },

  accessibility: {
    role: "region",
    summary: "Screen-reader figure region with programmatic title and automated factual metric summary (observation count, net delta, min/max bounds).",
    screenReader: "VoiceOver and NVDA announce the chart region and summary without traversing dozens of raw SVG nodes.",
    keyboardShortcuts: [
      { key: "Tab", action: "Focus chart interaction surface with visible focus ring" },
      { key: "ArrowLeft", action: "Select previous data observation" },
      { key: "ArrowRight", action: "Select next data observation" },
      { key: "Home", action: "Jump to first data point" },
      { key: "End", action: "Jump to last data point" },
      { key: "Escape", action: "Clear active selection" },
    ],
    colorIndependence: "Active point renders an enlarged concentric marker; tooltips provide explicit alphanumeric readout.",
    reducedMotion: "Automatically suppresses stroke draw animation when user requests reduced motion.",
  },

  sourceAnatomy: {
    tree: {
      name: "SignalLine",
      role: "Root figure wrapper",
      description: "Provides keyboard navigation, accessible figcaption summary, and responsive boundaries.",
      children: [
        {
          name: "ChartContainer",
          role: "CSS token bridge",
          description: "Scoped CSS variables for axes, grid, and crosshairs without global pollution.",
          children: [
            {
              name: "ResponsiveContainer",
              role: "Auto-sizing viewport",
              description: "Recharts container measuring width and height via ResizeObserver.",
              children: [
                { name: "LineChart", role: "SVG coordinator", description: "Calculates coordinate systems and margin offsets." },
                { name: "CartesianGrid", role: "Reference structure", description: "Subtle dashed horizontal dividers." },
                { name: "XAxis / YAxis", role: "Coordinate scales", description: "Adaptive font size, zero ticklines, tabular numbers." },
                { name: "Tooltip (ChartTooltip)", role: "Interactive inspector", description: "Glassmorphic card with formatted values." },
                { name: "Line", role: "Visual data curve", description: "Interpolated stroke with active dot marker." },
              ],
            },
          ],
        },
      ],
    },
    sourceFiles: [
      { path: "components/charts/recharts/line-signal.tsx", description: "Primary SignalLine React component implementation" },
      { path: "components/charts/shared/chart-container.tsx", description: "CSS variable token bridge and container wrapper" },
      { path: "components/charts/shared/chart-tooltip.tsx", description: "Tabular numerical inspection card" },
      { path: "components/charts/shared/chart-state.tsx", description: "Loading, empty, and error fallback states" },
      { path: "components/charts/shared/use-chart-reduced-motion.ts", description: "prefers-reduced-motion media query hook" },
    ],
    registryDependencies: ["chart-container", "chart-tooltip", "chart-state", "use-chart-reduced-motion"],
    npmDependencies: ["recharts"],
  },
}
