import type { ChartDetailDoc } from "./types"

export const lineTwinCompareDoc: ChartDetailDoc = {
  chartId: "recharts-line-twin-compare",
  engine: "recharts",
  category: "line",
  renderer: "svg",
  status: "preview",
  blueprint: "RECHARTS / LINE / COMPARATIVE / PREVIEW",

  quickFacts: {
    bestFor: "Actual vs target, current year vs previous year, canary release vs baseline, or primary metric vs benchmark.",
    dataModel: "Readonly array of observation records with a shared horizontal domain and two numeric series.",
    interaction: "Synchronized nearest-X crosshair, dual active dots, comparative tooltip with signed delta math.",
    responsive: "Single shared honest Y-scale (no dual axes), adaptive X-axis tick thinning, zero page overflow.",
    animation: "Synchronized dual-stroke reveal (350ms ease-out), respects prefers-reduced-motion.",
    runtime: "Recharts SVG (source owned, zero Plotcn runtime packages).",
  },

  dataFormat: {
    summary: "Accepts a readonly array of objects containing a horizontal coordinate and two distinct numeric series: primary (solid 2.5px) and reference (dashed 1.8px).",
    fields: [
      {
        field: "xKey",
        type: "string | number | Date",
        required: true,
        description: "Horizontal domain coordinate representing time, period, or an ordered discrete category.",
      },
      {
        field: "primaryKey",
        type: "number | null | undefined",
        required: true,
        description: "Primary numeric observation (e.g. current year, actual performance, canary release). Rendered with solid stroke.",
      },
      {
        field: "referenceKey",
        type: "number | null | undefined",
        required: true,
        description: "Reference baseline metric (e.g. prior year, budget target, production control). Rendered with dashed stroke.",
      },
    ],
    nullPolicy: "Truthful gap policy: missing observations produce an explicit break in stroke and are never coerced to zero.",
    orderingPolicy: "Caller must supply observations in ascending chronological or ordinal sequence.",
    exampleRows: [
      { period: "Jan", current: 180, previous: 120 },
      { period: "Feb", current: 240, previous: 190 },
      { period: "Mar", current: 310, previous: 220 },
      { period: "Apr", current: 280, previous: 260 },
      { period: "May", current: 390, previous: 310 },
      { period: "Jun", current: 460, previous: 380 },
    ],
  },

  props: [
    {
      name: "data",
      type: "readonly TData[]",
      default: "[]",
      required: true,
      category: "core",
      description: "Readonly array of comparative observation records. Caller data is never mutated.",
      bestFor: "Comparative dataset",
    },
    {
      name: "xKey",
      type: "keyof TData & string",
      default: "—",
      required: true,
      category: "core",
      description: "Property name for the horizontal X-axis domain (e.g. date, month, or sprint).",
      bestFor: "Domain coordinates",
    },
    {
      name: "primaryKey",
      type: "keyof TData & string",
      default: '"current"',
      required: false,
      category: "core",
      description: "Field name for the primary metric series to plot with solid emphasis.",
      bestFor: "Current/actual metric",
    },
    {
      name: "referenceKey",
      type: "keyof TData & string",
      default: '"previous"',
      required: false,
      category: "core",
      description: "Field name for the reference baseline series to plot with dashed styling.",
      bestFor: "Prior/benchmark metric",
    },
    {
      name: "primaryLabel",
      type: "string",
      default: '"Primary"',
      required: false,
      category: "visual",
      description: "Human-readable label for the primary series displayed in tooltips and legends.",
      bestFor: "Series identification",
    },
    {
      name: "referenceLabel",
      type: "string",
      default: '"Reference"',
      required: false,
      category: "visual",
      description: "Human-readable label for the reference series displayed in tooltips and legends.",
      bestFor: "Benchmark identification",
    },
    {
      name: "primaryColor",
      type: "string",
      default: '"var(--chart-1, #10b981)"',
      required: false,
      category: "visual",
      description: "Color token for the primary solid series stroke.",
      bestFor: "Primary brand theme",
      previewable: true,
      controlType: "segmented",
      controlOptions: [
        { value: "var(--chart-1, #10b981)", label: "Emerald" },
        { value: "#0ea5e9", label: "Sky" },
        { value: "#8b5cf6", label: "Purple" },
        { value: "#f59e0b", label: "Amber" },
      ],
    },
    {
      name: "referenceColor",
      type: "string",
      default: '"var(--chart-2, #94a3b8)"',
      required: false,
      category: "visual",
      description: "Color token for the reference dashed series stroke.",
      bestFor: "Benchmark stroke styling",
      previewable: true,
      controlType: "segmented",
      controlOptions: [
        { value: "var(--chart-2, #94a3b8)", label: "Slate" },
        { value: "#71717a", label: "Zinc" },
        { value: "#f59e0b", label: "Amber" },
        { value: "#f43f5e", label: "Rose" },
      ],
    },
    {
      name: "deltaType",
      type: '"both" | "percentage" | "absolute"',
      default: '"both"',
      required: false,
      category: "interaction",
      description: "Format of delta calculation in the comparative tooltip.",
      bestFor: "Comparative inspection detail",
      previewable: true,
      controlType: "segmented",
      controlOptions: [
        { value: "both", label: "Both (+$60 / +50%)" },
        { value: "percentage", label: "Percentage (+50%)" },
        { value: "absolute", label: "Absolute (+$60)" },
      ],
    },
    {
      name: "curve",
      type: '"monotone" | "linear" | "step"',
      default: '"monotone"',
      required: false,
      category: "visual",
      description: "Line interpolation across observations. Monotone for continuous trends; step for scheduled tiers.",
      bestFor: "Interpolation style",
      previewable: true,
      controlType: "segmented",
      controlOptions: [
        { value: "monotone", label: "Monotone" },
        { value: "linear", label: "Linear" },
        { value: "step", label: "Step" },
      ],
    },
    {
      name: "showLegend",
      type: "boolean",
      default: "true",
      required: false,
      category: "visual",
      description: "Whether to render the series comparison legend with solid vs dashed line indicators.",
      bestFor: "Multi-series clarity",
      previewable: true,
      controlType: "segmented",
      controlOptions: [
        { value: true, label: "Legend On" },
        { value: false, label: "Legend Off" },
      ],
    },
    {
      name: "showGrid",
      type: "boolean",
      default: "true",
      required: false,
      category: "visual",
      description: "Whether to render subtle horizontal background reference gridlines.",
      bestFor: "Grid density control",
      previewable: true,
      controlType: "segmented",
      controlOptions: [
        { value: true, label: "Grid On" },
        { value: false, label: "Grid Off" },
      ],
    },
    {
      name: "height",
      type: "number | string",
      default: "340",
      required: false,
      category: "core",
      description: "Container height in pixels or standard CSS dimension strings.",
      bestFor: "Dashboard slot sizing",
      previewable: true,
      controlType: "segmented",
      controlOptions: [
        { value: 260, label: "Compact (260px)" },
        { value: 340, label: "Default (340px)" },
        { value: 420, label: "Spacious (420px)" },
      ],
    },
    {
      name: "missingValuePolicy",
      type: '"gap" | "connect"',
      default: '"gap"',
      required: false,
      category: "core",
      description: "Handling of null or undefined observations. 'gap' preserves visual breaks; 'connect' bridges adjacent points.",
      bestFor: "Data safety & truthful representation",
      previewable: true,
      controlType: "segmented",
      controlOptions: [
        { value: "gap", label: "Gap (Truthful)" },
        { value: "connect", label: "Connect (Bridge)" },
      ],
    },
    {
      name: "domain",
      type: '[number, number] | ["auto", "auto"]',
      default: '"auto"',
      required: false,
      category: "core",
      description: "Explicit Y-axis numeric domain spanning both series, or 'auto' unified scale calculation.",
    },
    {
      name: "showXAxis",
      type: "boolean",
      default: "true",
      required: false,
      category: "visual",
      description: "Whether to display the horizontal X-axis tick labels.",
    },
    {
      name: "showYAxis",
      type: "boolean",
      default: "true",
      required: false,
      category: "visual",
      description: "Whether to display the unified vertical Y-axis scale.",
    },
    {
      name: "motion",
      type: "boolean | { duration?: number }",
      default: "true",
      required: false,
      category: "visual",
      description: "Synchronized dual-line reveal animation (350ms). Automatically disabled under prefers-reduced-motion.",
    },
    {
      name: "title",
      type: "string",
      default: '"Twinline Compare"',
      required: false,
      category: "a11y",
      description: "Accessible name announced to screen-readers for the chart figure region.",
    },
    {
      name: "description",
      type: "string",
      default: "undefined",
      required: false,
      category: "a11y",
      description: "Long-form context describing what the comparative trend communicates.",
    },
    {
      name: "loading",
      type: "boolean",
      default: "false",
      required: false,
      category: "advanced",
      description: "Renders a neutral loading skeleton preserving container footprint without fake data.",
    },
    {
      name: "error",
      type: "Error | string | null",
      default: "null",
      required: false,
      category: "advanced",
      description: "Renders an actionable error state banner with optional retry trigger.",
    },
    {
      name: "unavailable",
      type: "boolean | string | null",
      default: "false",
      required: false,
      category: "advanced",
      description: "Renders a metric unavailability notice (e.g. permission restriction or retention limit).",
    },
  ],

  examples: [
    {
      id: "annual-benchmark",
      title: "Year-Over-Year Performance",
      description: "Primary 2024 performance contrasted against dashed 2023 baseline with synchronized delta calculation.",
      snippet: `<TwinlineCompare data={revenueData} xKey="month" primaryKey="actual2024" referenceKey="prior2023" primaryLabel="2024 Actual" referenceLabel="2023 Prior" />`,
      props: { primaryLabel: "2024 Actual", referenceLabel: "2023 Prior", height: 260 },
    },
    {
      id: "percentage-delta",
      title: "Relative Percentage Variance",
      description: "Focuses comparative tooltip inspection strictly on percentage delta (+25.0%) without clutter.",
      snippet: `<TwinlineCompare data={latencyData} xKey="period" primaryKey="canary" referenceKey="baseline" deltaType="percentage" />`,
      props: { deltaType: "percentage", height: 260 },
    },
    {
      id: "step-comparison",
      title: "Scheduled Rate Tiers vs Observed",
      description: "Discrete step interpolation comparing actual billing usage against contracted rate limits.",
      snippet: `<TwinlineCompare data={tierData} xKey="hour" primaryKey="usage" referenceKey="limit" curve="step" primaryColor="#0ea5e9" referenceColor="#71717a" />`,
      props: { curve: "step", primaryColor: "#0ea5e9", referenceColor: "#71717a", height: 260 },
    },
    {
      id: "compact-tile",
      title: "Compact Overview Widget",
      description: "Condensed 200px tile comparison with clean legend and unified scale for executive summary cards.",
      snippet: `<TwinlineCompare data={metrics} xKey="month" primaryKey="mrr" referenceKey="target" showYAxis={false} height={200} />`,
      props: { showYAxis: false, primaryColor: "#10b981", referenceColor: "#94a3b8", height: 200 },
    },
  ],

  responsive: {
    overview: "Twinline Compare scales primary and reference curves synchronously on a single honest Y-axis. The synchronized tooltip card automatically formats metric readouts and delta calculations without viewport overflow.",
    breakpoints: [
      { name: "Desktop", width: ">= 1024px", behavior: "Full comparative tooltip with signed delta and percentage change, explicit legend with solid vs dashed indicator." },
      { name: "Tablet", width: "640px - 1023px", behavior: "Thinned X-axis labels, preserved line continuity, compact margins, tooltip pinned within viewport boundaries." },
      { name: "Mobile", width: "< 640px", behavior: "Edge-to-edge scrub inspection, compact legend pills, touch-first scrub interaction." },
    ],
  },

  animation: {
    overview: "Both primary and reference lines draw synchronously on initial mount (350ms). Theme switches, container resize, and prop changes transition smoothly without geometry flicker.",
    duration: "350ms ease-out",
    refreshable: true,
  },

  interaction: {
    tooltip: "Plotcn comparative tooltip displaying primary value, reference value, and calculated signed delta (e.g. +$40k / +25.0%).",
    crosshair: "Vertical dashed guideline intersecting both primary and reference points simultaneously.",
    legend: "Interactive legend highlighting primary (solid line) and reference (dashed line) series semantics.",
  },

  accessibility: {
    role: "region",
    summary: "Screen-reader figure region with quantitative delta summary (net change across both primary and benchmark series).",
    screenReader: "VoiceOver and NVDA announce primary vs reference series values and comparative delta without SVG node traversal.",
    keyboardShortcuts: [
      { key: "Tab", action: "Focus comparative chart region with prominent focus ring" },
      { key: "ArrowLeft", action: "Step to previous comparative observation" },
      { key: "ArrowRight", action: "Step to next comparative observation" },
      { key: "Home", action: "Jump to first observation point" },
      { key: "End", action: "Jump to latest observation point" },
      { key: "Escape", action: "Clear active inspection state" },
    ],
    colorIndependence: "Primary line is solid 2.5px while reference line is dashed 1.8px (dasharray 4 3), ensuring full clarity without relying on color.",
    reducedMotion: "Automatically suppresses stroke draw animation when user requests reduced motion.",
  },

  sourceAnatomy: {
    tree: {
      name: "TwinlineCompare",
      role: "Root figure wrapper",
      description: "Provides comparative keyboard navigation, accessible delta summary, and responsive boundaries.",
      children: [
        {
          name: "ChartContainer",
          role: "CSS token bridge",
          description: "Scoped CSS variables for axes, grid, and crosshairs without global pollution.",
          children: [
            {
              name: "ResponsiveContainer",
              role: "Auto-sizing viewport",
              description: "Recharts container measuring width and height via ResizeObserver.",
              children: [
                { name: "LineChart", role: "SVG coordinator", description: "Calculates shared unified coordinate scale across both series." },
                { name: "CartesianGrid", role: "Reference structure", description: "Subtle dashed horizontal dividers." },
                { name: "XAxis / YAxis", role: "Coordinate scales", description: "Single honest Y scale preventing dual-axis scale deception." },
                { name: "Tooltip (ComparisonTooltip)", role: "Comparative inspector", description: "Card with primary, reference, and signed delta values." },
                { name: "Line (Primary)", role: "Dominant curve", description: "Solid 2.5px stroke with active dot marker." },
                { name: "Line (Reference)", role: "Benchmark baseline", description: "Dashed 1.8px stroke (strokeDasharray: '4 3')." },
                { name: "Legend (ChartLegend)", role: "Visual key", description: "Distinguishes primary vs reference semantics." },
              ],
            },
          ],
        },
      ],
    },
    sourceFiles: [
      { path: "components/charts/recharts/line-twin-compare.tsx", description: "Primary TwinlineCompare comparative visualization component" },
      { path: "components/charts/shared/chart-container.tsx", description: "CSS variable token bridge and container wrapper" },
      { path: "components/charts/shared/chart-tooltip.tsx", description: "Tabular numerical inspection card" },
      { path: "components/charts/shared/chart-legend.tsx", description: "Solid vs dashed comparison legend" },
      { path: "components/charts/shared/chart-state.tsx", description: "Loading, empty, and error fallback states" },
      { path: "components/charts/shared/use-chart-reduced-motion.ts", description: "prefers-reduced-motion media query hook" },
    ],
    registryDependencies: ["chart-container", "chart-tooltip", "chart-legend", "chart-state", "use-chart-reduced-motion"],
    npmDependencies: ["recharts"],
  },
}
