"use client"
import { useState } from "react"
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Button } from "@/components/ui/button"
import { ChartPreview } from "./chart-preview"
import { Icon } from "./icons"
import { CopyButton } from "./copy-button"

const blockData = {
  analytics:{title:"Analytics overview",subtitle:"A little perspective on the big picture.",metrics:[["Total sessions","42,860","+12.8%"],["Active visitors","8,420","+8.2%"],["Avg. session","3m 42s","+4.1%"]],chart:"area",second:"donut",rows:[["Direct","18,420","43%"],["Organic search","14,230","33%"],["Referral","10,210","24%"]]},
  financial:{title:"Portfolio overview",subtitle:"The movement behind your numbers.",metrics:[["Portfolio value","$128,450","+6.4%"],["Net deposits","$24,000","+2.1%"],["Positions","12","3 asset types"]],chart:"candles",second:"treemap",rows:[["Equities","$77,070","60%"],["Bonds","$32,113","25%"],["Cash","$19,267","15%"]]},
  operations:{title:"Operations overview",subtitle:"A clear view of the work in motion.",metrics:[["Requests","284,120","+18.2%"],["Success rate","99.8%","+0.2%"],["Avg. latency","142 ms","−12 ms"]],chart:"line",second:"heatmap",rows:[["API","180,400","63%"],["Workers","72,100","25%"],["Scheduled","31,620","12%"]]},
} as const
export function BlocksSection() {
  const [block,setBlock]=useState<keyof typeof blockData>("analytics")
  const data=blockData[block]
  const code=`<div className="grid gap-6 md:grid-cols-2">\n  <div style={{ height: 280 }}>\n    ${data.chart === "area" || data.chart === "line" ? `<PlotLineChart data={data} area={${data.chart === "area"}} />` : '<D3Plot kind="candles" />'}\n  </div>\n  <div style={{ height: 280 }}>\n    <D3Plot kind="${data.second}" />\n  </div>\n</div>`
  return <section id="blocks" className="section blocks-section site-container"><div className="section-topline"><span className="eyebrow">07 / THE BIGGER PICTURE</span><span className="section-note">COMPONENTS, IN GOOD COMPANY</span></div><div className="section-heading"><div><h2>Start with a chart.<br /><span>Build the whole view.</span></h2><p>Combine the same building blocks into an interface that works together.</p></div><Tabs value={block} onValueChange={value=>setBlock(value as keyof typeof blockData)}><TabsList aria-label="Dashboard example"><TabsTrigger value="analytics">Analytics</TabsTrigger><TabsTrigger value="financial">Financial</TabsTrigger><TabsTrigger value="operations">Operations</TabsTrigger></TabsList></Tabs></div><div className="dashboard-block"><aside className="dashboard-sidebar"><span className="dashboard-brand"><Icon name="layers" />Workspace</span><span className="dashboard-nav-active"><Icon name="chart" />Overview</span><span><Icon name="layers" />Reports</span><span><Icon name="code" />Integrations</span><div>COMPOSITION PREVIEW<br />Sample data</div></aside><div className="dashboard-main"><div className="dashboard-heading"><div><h3>{data.title}</h3><p>{data.subtitle}</p></div><span className="engine-pill">DEMO DATA</span></div><div className="dashboard-metrics">{data.metrics.map(([label,value,change])=><div key={label}><span>{label}</span><strong>{value}</strong><small>{change} <span>vs. previous</span></small></div>)}</div><div className="dashboard-charts"><div><h4>{block==="financial"?"Price movement":"Activity over time"}</h4><div><ChartPreview kind={data.chart} /></div></div><div><h4>{block==="operations"?"Request rhythm":"Distribution"}</h4><div><ChartPreview kind={data.second} compact /></div></div></div><div className="dashboard-table"><table><caption className="sr-only">Sample {block} breakdown</caption><thead><tr><th>Source</th><th>Value</th><th>Share</th></tr></thead><tbody>{data.rows.map(([name,value,share])=><tr key={name}><td>{name}</td><td>{value}</td><td>{share}</td></tr>)}</tbody></table></div></div></div><div className="block-caption"><span>A composition of the components above. Nothing hidden.</span><div><Button variant="ghost" onClick={()=>document.getElementById("charts")?.scrollIntoView({behavior:"instant"})}>Explore the components<Icon name="arrow" /></Button><CopyButton value={code} label="Copy dashboard composition" /></div></div></section>
}
